### PR TITLE
URGENT UPDATE

### PR DESCRIPTION
**Pull request by eggsywashere**
VERY URGENT. VERY.

### CODE REVIEW

**Comment by eggsywashere** [comment]
uplod gogle very fast.
people wait.

**Comment by Timeraa** [comment]
No u

**Comment by Fruxh** [comment]
no u

**Comment by eggsywashere** [comment]
YES EXACTLY. I WATI.. UPLOD GOGLE.

**Comment by Timeraa** [comment]
Can yUj SpeCh Eglich?

**Comment by eggsywashere** [comment]
no, can yu uplod?

**Comment by Timeraa** [comment]
Never

**Comment by Timeraa** [comment]
Idk

**Comment by Timeraa** [comment]
To late

**Comment by emirkabal** [comment]
hi

**Comment by Timeraa** [comment]
> hi

That was unexpected

**Comment by eggsywashere** [comment]
pls :< urgent. veri.

**Comment by emirkabal** [comment]
> > hi
> 
> That was unexpected

absolutely

**Comment by Timeraa** [comment]
tenor

**Comment by emirkabal** [comment]
i am gay

**Comment by eggsywashere** [comment]
[porn](https://tenor.com/view/choro-lagrimas-bico-chateada-gif-6165001)

**Comment by eggsywashere** [comment]
porn

**Comment by eggsywashere** [comment]
tf

**Comment by emirkabal** [comment]
`I AM GAY`

**Comment by eggsywashere** [comment]
tenor

**Comment by emirkabal** [comment]
ok

**Comment by emirkabal** [comment]
lmao

**Comment by eggsywashere** [comment]
ASSIGN AND GIV YOUR GOGLE ACOUNT

**Comment by emirkabal** [comment]
gogle

**Comment by emirkabal** [comment]
冠状病毒

**Comment by Timeraa** [comment]
image

**Comment by eggsywashere** [comment]
ok so this is asinged me.
i order @Timeraa to uplod new version IMMEDIAATIYL NAO!! 😡😡😡💢👿

**Comment by eggsywashere** [comment]
öpen!

**Comment by Timeraa** [comment]
image
The good old days of PreMiD

**Comment by eggsywashere** [comment]
the good and ugly new days BRO MERGE THIS AND UPLOAD OK and merge [THİS](https://github.com/PreMiD/Extension/pull/7) too

**Comment by eggsywashere** [comment]
forgot to upload the picture: here good and ugly new days:
image

**Comment by Timeraa** [comment]
image
More uglier future 
image

**Comment by eggsywashere** [comment]
yes really why even change theme still dont get it
upload .

**Comment by emirkabal** [comment]
gn

**Pull request closed without merging**
