### PR TITLE
Make getPageletiable accept custom JS

### PR DESCRIPTION
**Pull request by spencerpogo**
Make getPageletiable accept custom JS and remove JSON requirement.

### CODE REVIEW

**Comment by Timeraa** [comment]
Sorry that I kinda forgot about this.... Can you make sure it can also accept a variable name?

**Comment by Scoder12** [comment]
What do you mean variable?

**Comment by Timeraa** [comment]
So that you can get a variable like "ytplayer" from the dom without having to put a whole script into it

**Comment by Scoder12** [comment]
I think this would work with my current code. The way it works is just resolving with `(code)` instead of requiring it to be a value in `window`, so I think it supports what you're describing and it won't break any existing usage.

Also I kinda deleted the branch already.

**Pull request closed without merging**
