### PR TITLE
:fire: CSS improvements, change the way detection works = better.

### PR DESCRIPTION
**Pull request by eggsywashere**
new overlay

Screenshot_20200506_064536

### CODE REVIEW

**Comment by doomlerd** [comment]
*that yt logo doe*

**Comment by eggsywashere** [comment]
> *that yt logo doe*

I just fixed their height I don't take any responsibilities.

**Comment by Timeraa** [comment]
Too much padding

**Comment by eggsywashere** [comment]
it better

**Comment by Timeraa** [comment]
@eggsywashere It really isn't, I think a lot of people can agree with that.

**Comment by eggsywashere** [comment]
> @eggsywashere It really isn't, I think a lot of people can agree with that.

Get some screenshots and do a poll :kekw:

**Comment by Timeraa** [comment]
image

**Pull request closed without merging**
